services:

  redis:
    image: redis:7-alpine
    container_name: hybrid-rag-redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.16.3
    container_name: hybrid-rag-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-api:
    build: .
    container_name: hybrid-rag-api
    depends_on:
      - redis
      - qdrant
    ports:
      - "8021:8021"
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379/0
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION_ALIAS: sec_filings_chunks_current
    restart: unless-stopped
    command: >
      gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      -w 2
      -t 300
      -b 0.0.0.0:8021

  rag-frontend:
    build:
      context: ./frontend
    container_name: hybrid-rag-frontend
    depends_on:
      - rag-api
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://rag-api:8021
    restart: unless-stopped

volumes:
  qdrant_data:
